### ISSUE TITLE
Look at Workshop on Ethics in Networked Systems Research

### ISSUE THREAD

**Issue by irl** [IRTF-PEARG/draft-safe-internet-measurement#1]
Lars Eggert suggested the following workshop to look at for prior work in this space:

http://conferences.sigcomm.org/sigcomm/2015/netethics.php

**Comment by mallory** [comment]
Reviewed these and used those that seemed relevant. This is certainly a ripe list for examples, in particular:
* The Chokepoint Project’s mission is to perform continuous monitoring of network behavior in conjunction with legal data, journalistic events and econometric data to provide up to date and contextualized information about human and civil rights in a digital environment. http://conferences.sigcomm.org/sigcomm/2015/pdf/papers/nsethics/p1.pdf
