### ISSUE TITLE
Safety != Ethics

### ISSUE THREAD

**Issue by irl-erg** [IRTF-PEARG/draft-safe-internet-measurement#6]
Feedback so far has been talking about how there has been much prior work on ethics of Internet measurement, which is true, but I think it is not clear in the document that this is primarily aiming to discuss safety which is a far narrower scope than ethics.

**Comment by irl-erg** [comment]
Rough working definition of "safety":

> When performing research on a platform shared with live traffic from other users, that research is considered safe if and only if other users are protected from or unlikely to experience danger, risk, or injury, now or in the future, due to the research.

**Comment by irl-erg** [comment]
http://conferences.sigcomm.org/sigcomm/2015/pdf/papers/nsethics/p17.pdf

> The first, most basic point to note is that universities and research organizations do not currently have review boards equipped to evaluate these research methods. IRBs evaluate research protocols relating to “human subjects” experiments, which describe a specific type of research involving intervention with people, typically to collect individualized data directly from them.  Measurement of the technical specifics of censorship (what content the censor blocks, and technically how they impose the blocking) falls outside of human subjects research, and thus outside the purview of university IRBs. Yet, although the experiments do not involve human subjects, they nonetheless involve potential risk to people.

**Comment by mallory** [comment]
Closed as per recent commit.
